version: '3.9'

networks:
  proxy:
    external: true

volumes:
  database:
  data:

services:
  db:
    image: mariadb:10.3
    restart: unless-stopped
    container_name: vaultwarden-db
    networks:
      proxy:
        aliases:
         - vaultwarden_db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - database:/var/lib/mysql
      - "/etc/localtime:/etc/localtime:ro"

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      proxy:
    environment:
      WEBSOCKET_ENABLED: "true"  # Enable WebSocket notifications
      ADMIN_TOKEN: "${ADMIN_TOKEN}"
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@vaultwarden_db/${MYSQL_DATABASE}"
      RUST_BACKTRACE: 1
      SIGNUPS_ALLOWED: "false"  # remove registrations
      INVITATIONS_ALLOWED: "true"
      INVITATION_ORG_NAME: MCIA
      DOMAIN: "${VAULTWARDEN_DOMAIN}"
      SMTP_FROM: "${SMTP_FROM}"
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_SECURITY: "off"
      SMTP_TIMEOUT: "${SMTP_TIMEOUT}"
    volumes:
      - data:/data
    labels:
      - "traefik.enable=true"

      # UI
      - "traefik.http.routers.vaultwarden-ui.rule=PathPrefix(`/vaultwarden`)"
      - "traefik.http.routers.vaultwarden-ui.entrypoints=websecure"
      - "traefik.http.services.vaultwarden-ui.loadbalancer.server.port=80"
      - "traefik.http.routers.vaultwarden-ui.service=vaultwarden-ui"

      # WebSocket notifications
      - "traefik.http.routers.vaultwarden-websocket.rule=PathPrefix(`/vaultwarden/notifications/hub`)"
      - "traefik.http.routers.vaultwarden-websocket.entrypoints=websecure"
      - "traefik.http.services.vaultwarden-websocket.loadbalancer.server.port=3012"
      - "traefik.http.routers.vaultwarden-websocket.service=vaultwarden-websocket"
