version: '3.9'

networks:
  proxy:
    external: true

volumes:
  database:
  gpg_volume:
  jwt_volume:

services:
  db:
    image: mariadb:10.3
    restart: unless-stopped
    container_name: passbolt-db
    networks:
      - proxy
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - database:/var/lib/mysql

  passbolt:
    image: passbolt/passbolt:latest-ce
    #Alternatively you can use rootless:
    #image: passbolt/passbolt:latest-ce-non-root
    restart: unless-stopped
    container_name: passbolt
    networks:
      - proxy
    depends_on:
      - db
    environment:
      APP_BASE: "${APP_BASE}"
      APP_FULL_BASE_URL: "${APP_FULL_BASE_URL}"
      PASSBOLT_SSL_FORCE: "FALSE"
      DATASOURCES_DEFAULT_HOST: "db"
      DATASOURCES_DEFAULT_USERNAME: "${MYSQL_USER}"
      DATASOURCES_DEFAULT_PASSWORD: "${MYSQL_PASSWORD}"
      DATASOURCES_DEFAULT_DATABASE: "${MYSQL_DATABASE}"
      EMAIL_DEFAULT_FROM: "${EMAIL_DEFAULT_FROM}"
      EMAIL_TRANSPORT_DEFAULT_HOST: "${EMAIL_TRANSPORT_DEFAULT_HOST}"
      EMAIL_TRANSPORT_DEFAULT_PORT: "${EMAIL_TRANSPORT_DEFAULT_PORT}"
      # EMAIL_TRANSPORT_DEFAULT_USERNAME: ""
      # EMAIL_TRANSPORT_DEFAULT_PASSWORD: ""
      # EMAIL_TRANSPORT_DEFAULT_SSL: ""
      EMAIL_TRANSPORT_DEFAULT_TIMEOUT: "${EMAIL_TRANSPORT_DEFAULT_TIMEOUT}"
    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
    command: ["/usr/bin/wait-for.sh", "-t", "0", "passbolt-db:3306", "--", "/docker-entrypoint.sh"]
    # ports:
    #   - 80:80
    #   - 443:443
    #Alternatively for non-root images:
    # - 80:8080
    # - 443:4433
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.passbolt.rule=PathPrefix(`/passbolt`)" # Host(`mcia04.upc.edu`)"
      # - "traefik.http.routers.passbolt.rule=Host(`passbolt.yourdomain.com`)"
      # strip /passbolt to work with path
      - "traefik.http.middlewares.remove-path-passbolt.stripprefix.prefixes=/passbolt"
      - "traefik.http.routers.passbolt.middlewares=remove-path-passbolt@docker"
      - "traefik.http.routers.passbolt.entrypoints=websecure"
      - "traefik.http.services.passbolt.loadbalancer.server.port=80"